(define (read-lines . args)
  (let ((p (cond ((null? args) (current-input-port))
                 ((port? (car args)) (car args))
                 ((string? (car args)) (open-input-file (car args)))
                 (else (error 'read-lines "bad argument")))))
    (let loop ((line (read-line p)) (lines (list)))
      (if (eof-object? line)
        (begin
          (if (and (pair? args) (string? (car args)))
            (close-input-port p))
          (reverse lines))
        (loop (read-line p) (cons (string->number line) lines))))))

(define (part-1 x a b)
  (if (and (not (null? a)) (= 2020 (+ (car a) (car b))))
    (list (car a) (car b) (* (car a) (car b)))
    (if (null? a)
      (if (null? b)
        0
        (part-1 x x (cdr b)))
      (part-1 x (cdr a) b))))

(define (part-2 x a b c)
  (if (and (not (null? a)) (not (null? b)) (= 2020 (+ (car a) (car b) (car c))))
    (list (car a) (car b) (car c) (* (car a) (car b) (car c)))
    (if (null? a)
      (if (null? b)
        (if (null? c)
          0
          (part-2 x a x (cdr c)))
        (part-2 x x (cdr b) c))
      (part-2 x (cdr a) b c))))

(define entries (read-lines "files/1.txt"))
(part-1 entries entries entries)
(part-2 entries entries entries entries)
