(define (read-lines file detail)
  (let ((infile (open-input-file file)))
    (let loop ((lines '())
        (next-line (read-line infile)))
    (if (eof-object? next-line)
      (begin (close-input-port infile)
          (reverse lines))
      (loop (cons (detail next-line) lines)
          (read-line infile))))))
